language: python
python:
  - "3.7"
sudo: true
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - chmod +x r-dir-script.sh
  - ./r-dir-script.sh

script:
  - pytest