language: r
r:
  - devel
r_packages:
  - devtools
  - testthat

apt_packages:
  - libxml2-dev
  - libcurl4-gnutls-dev
  
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

# Install python dependencies in this step
before_install:
  - chmod +x install-script.sh
  - chmod +x test-script.sh

install:
  - ./install-script.sh

script:
  - ./test-script.sh


# https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
notifications:
  email:
    recipients:
      - ankitgau@andrew.cmu.edu