language: r
r:
  - devel
r_packages:
  - devtools
  - testthat

apt_packages:
  - libxml2-dev
  - libcurl4-gnutls-dev
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

before_install:
  - python3 --version
  - sudo apt-get -y install python3-pip
  - pip3 install -U pip
  - pip3 install -U pytest
  - chmod +x r-dir-script.sh
  - ./r-dir-script.sh

script:
  - echo "Hello World"